In [1]:
import numpy

from src.perceptron.data.Preprocess import create_dataset, create_split, read_file
from src.perceptron.Model import Perceptron
from src.perceptron.network.LossFunction import MeanSquareError
from src.perceptron.Trainer import get_in_out_features

In [2]:
raw_dataset: list = read_file("../data/extra/2Circle2.txt")

In [3]:
dataset = create_dataset(raw_dataset)

In [4]:
dataset_split = create_split(dataset, [2 / 3, 1 / 3])

In [5]:
in_feature, out_feature = get_in_out_features(dataset)

In [6]:
model = Perceptron(in_feature, out_feature, 0.05)
loss_function = MeanSquareError()

In [7]:
label_predicted: list = []

In [8]:
len(dataset_split["train"])

173

In [9]:
160 - 53 * 3

1

In [10]:
i: int = 0
for row in dataset_split["train"].iter_slices(3):
	print(i)
	i += 1
	data, one_hot_label = row["data"].to_numpy(), row["one_hot_label"].to_numpy()
	output = model(data)
	label_predicted += output.argmax(-1).tolist()
	loss = loss_function(output, one_hot_label)
	model.optimize(loss_function.gradient)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57


In [11]:
a = numpy.random.rand(2, 3)

In [12]:
b = numpy.random.rand(2, 3)

In [13]:
a

array([[0.62986764, 0.91350337, 0.42087061],
       [0.5915152 , 0.6917374 , 0.02935293]])

In [14]:
c = a * b

In [15]:
c.shape

(2, 3)

In [16]:
a

array([[0.62986764, 0.91350337, 0.42087061],
       [0.5915152 , 0.6917374 , 0.02935293]])

In [17]:
a + numpy.random.rand(1)

array([[1.58484997, 1.8684857 , 1.37585295],
       [1.54649754, 1.64671973, 0.98433526]])

In [18]:
a

array([[0.62986764, 0.91350337, 0.42087061],
       [0.5915152 , 0.6917374 , 0.02935293]])

In [19]:
a = numpy.ones((3, 1))
a

array([[1.],
       [1.],
       [1.]])

In [20]:
b = numpy.random.rand(3, 4)
b

array([[0.01347244, 0.95934672, 0.61365761, 0.27243712],
       [0.57250104, 0.08539969, 0.46830205, 0.39208748],
       [0.09492381, 0.35651497, 0.12922487, 0.22636752]])

In [21]:
a.T.dot(b)

array([[0.6808973 , 1.40126138, 1.21118454, 0.89089212]])

In [22]:
b.sum(0)

array([0.6808973 , 1.40126138, 1.21118454, 0.89089212])